name: airbnb 개발용 CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches:
#     - BE
#   pull_request:
#     branches:
#     - BE
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildAndDeploy:
    name: dev-deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      working-directory: ./be

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '11'
          distribution: 'zulu'
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./be/gradlew
        shell: bash
      
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.7
