name: airbnb 개발용 CI

on:
  workflow_dispatch:
  
jobs:
  buildAndDeploy:
    name: dev-deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      WORKING_DIR: ./be
      S3_BUCKET_NAME: airbnb-deploy
      PROJECT_NAME: airbnb
      AWS_REGION: ap-northeast-2
      CODE_DEPLOY_APPLICATION_NAME: codesquad-deploy


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '11'
          distribution: 'zulu'
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
        working-directory: ${{env.WORKING_DIR}}
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        working-directory: ${{env.WORKING_DIR}}
      
      # $GITHUB_SHA는 현재 workflow를 실행시키는 커밋의 해쉬값
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip .
        shell: bash
        working-directory: ${{env.WORKING_DIR}}
      
      # 저장소에 미리 저장해놓은 엑세스 키 ID, 비밀 엑세스 키, 지역 정보
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region $AWS_REGION ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
        working-directory: ${{env.WORKING_DIR}}

      # CodeDeply 관련 설정
      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APPLICATION_NAME --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip
        working-directory: ${{env.WORKING_DIR}}
